// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD37Hz7g_dLjDOYoXvLG-I4TA2caWMKhxY',
    appId: '1:148474411029:web:eb434a95b6237ec869761c',
    messagingSenderId: '148474411029',
    projectId: 'test-firebase-sign',
    authDomain: 'test-firebase-sign.firebaseapp.com',
    storageBucket: 'test-firebase-sign.appspot.com',
    measurementId: 'G-RYK2Y9FXBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARRr-2TItMYUUg2omrLbN1ES06yqOT9WU',
    appId: '1:148474411029:android:8b42c84157bd571e69761c',
    messagingSenderId: '148474411029',
    projectId: 'test-firebase-sign',
    storageBucket: 'test-firebase-sign.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF9b_SnupOQmNVlcA6aBQDWef4Ex5VKmw',
    appId: '1:148474411029:ios:734056b1be36af7069761c',
    messagingSenderId: '148474411029',
    projectId: 'test-firebase-sign',
    storageBucket: 'test-firebase-sign.appspot.com',
    iosClientId: '148474411029-5c95a2ggdepgk22ahjjfds2lsv9oid4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.quraanApp',
  );
}
